### ISSUE TITLE
Error if repository declaration is verbose

### ISSUE THREAD

**Issue by ghost** [easystatic/easystatic#3]
In `package.json` if you have a simple repository declaration like this then there are no issues:

``` json
{
    "repository": "http://github.com/easystatic/easystatic.git"
}
```

However, if you have a more verbose declaration like this:

``` json
{
    "repository": {
        "type": "git",
        "url": "git+https://github.com/easystatic/easystatic.git"
    }
}
```

Then you get the following strange error when you do `easystatic start docs`:

``` bash
> easystatic start docs

TypeError: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:53:11)
    at Object.exports.request (http.js:31:10)
    at Object.exports.request (https.js:199:15)
    at Object.exports.get (https.js:203:21)
    at /usr/local/lib/node_modules/easystatic/lib/info.js:11:23
    at /usr/local/lib/node_modules/easystatic/lib/info.js:9:12
    at next (native)
    at step (/usr/local/lib/node_modules/easystatic/lib/info.js:133:191)
    at /usr/local/lib/node_modules/easystatic/lib/info.js:133:451
    at /usr/local/lib/node_modules/easystatic/lib/info.js:133:99
    at tryFetch (/usr/local/lib/node_modules/easystatic/lib/info.js:38:16)
    at /usr/local/lib/node_modules/easystatic/lib/info.js:89:18
    at next (native)
    at step (/usr/local/lib/node_modules/easystatic/lib/info.js:133:191)
    at /usr/local/lib/node_modules/easystatic/lib/info.js:133:451
    at /usr/local/lib/node_modules/easystatic/lib/info.js:133:99
```

This is hard to debug and I only realized this by trial and error after wasting a few hours. The error should either be more obvious, or the verbose format should just be handled.

For now the workaround is to switch to the simpler syntax.

**Comment by ghost** [comment]
BTW, if you guys have any thoughts on [this issue](https://github.com/axis-tip/quran-promise/issues/7)... much appreciated. Thank you!
